'use client';

import { FormEvent,useState } from 'react';

export default function AuthPage(){
  const[mode,setMode]=useState<'sign-in'|'sign-up'>('sign-in'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false);
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError(null);try{const path=mode==='sign-in'?'/api/auth/sign-in/email':'/api/auth/sign-up/email';const body=mode==='sign-in'?{email,password}:{email,password,name};const r=await fetch(path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(!r.ok){const d=await r.json().catch(()=>null);throw new Error(d?.message??d?.error??'Authentification échouée');}window.location.href='/';}catch(err){setError(err instanceof Error?err.message:'Authentification échouée');}finally{setBusy(false);}}
  return <main className="min-h-screen bg-zinc-950 text-white grid place-items-center p-6"><form onSubmit={submit} className="w-full max-w-md rounded-2xl border border-zinc-800 bg-zinc-900 p-6"><h1 className="text-2xl font-bold">NexaForge</h1><p className="mt-1 text-sm text-zinc-400">{mode==='sign-in'?'Connexion sécurisée':'Créer ton compte'}</p>{mode==='sign-up'&&<input value={name} onChange={e=>setName(e.target.value)} placeholder="Nom" className="mt-6 w-full rounded-xl bg-zinc-800 p-3 outline-none" required/>}<input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="Email" className="mt-4 w-full rounded-xl bg-zinc-800 p-3 outline-none" required/><input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="Mot de passe" minLength={8} className="mt-4 w-full rounded-xl bg-zinc-800 p-3 outline-none" required/>{error&&<div className="mt-4 rounded-xl border border-red-900 bg-red-950/30 p-3 text-sm text-red-300">{error}</div>}<button disabled={busy} className="mt-5 w-full rounded-xl bg-white p-3 font-semibold text-black disabled:opacity-50">{busy?'Patiente…':mode==='sign-in'?'Se connecter':'Créer le compte'}</button><button type="button" onClick={()=>setMode(mode==='sign-in'?'sign-up':'sign-in')} className="mt-4 w-full text-sm text-zinc-400">{mode==='sign-in'?'Créer un compte':'J’ai déjà un compte'}</button></form></main>;
}
