import { neon, type NeonQueryFunction } from '@neondatabase/serverless';

export type TaskRecord = { id:string; prompt:string; mode:string; status:string; workspaceId:string; maxIterations:number; budgetCents?:number|null; result?:unknown; errorCode?:string|null; iterationCount:number; createdAt:string; completedAt?:string|null };
export type CreateTaskInput = { prompt:string; mode:string; workspaceId:string; maxIterations?:number; budgetCents?:number };
export type TaskEventRecord = { id:string; taskId:string; type:string; payload:unknown; createdAt:string };
export type WorkspaceRecord = { id:string; name:string; ownerId:string; createdAt:string };
export type UserRecord = { id:string; email:string; displayName?:string|null };
export type WorkspaceRole = 'owner'|'admin'|'member'|'viewer';
export type ApprovalRecord = { id:string; taskId:string; workspaceId:string; toolCallId?:string|null; tool:string; input:unknown; status:string; requestedBy?:string|null; decidedBy?:string|null; reason?:string|null; createdAt:string; decidedAt?:string|null };

export interface TaskRepository {
  create(input:CreateTaskInput):Promise<TaskRecord>; get(id:string):Promise<TaskRecord|null>; claimNextQueued():Promise<TaskRecord|null>; updateStatus(id:string,status:string):Promise<TaskRecord|null>; updateExecution(id:string,input:{status:string;result?:unknown;errorCode?:string;iterationCount:number}):Promise<TaskRecord|null>; addEvent(taskId:string,type:string,payload:unknown):Promise<TaskEventRecord>; listEvents(taskId:string):Promise<TaskEventRecord[]>; createWorkspace(input:{email:string;displayName?:string;workspaceName?:string}):Promise<WorkspaceRecord>; workspaceExists(id:string):Promise<boolean>;
  getUserByEmail(email:string):Promise<UserRecord|null>; getWorkspaceRole(workspaceId:string,userId:string):Promise<WorkspaceRole|null>; createApproval(input:{taskId:string;workspaceId:string;toolCallId?:string;tool:string;input:unknown}):Promise<ApprovalRecord>; listApprovals(workspaceId:string,status?:string):Promise<ApprovalRecord[]>; decideApproval(id:string,userId:string,status:'approved'|'rejected',reason?:string):Promise<ApprovalRecord|null>;
}

const toTask=(r:Record<string,unknown>):TaskRecord=>({id:String(r.id),prompt:String(r.prompt),mode:String(r.mode),status:String(r.status),workspaceId:String(r.workspace_id),maxIterations:Number(r.max_iterations??12),budgetCents:r.budget_cents===null?null:Number(r.budget_cents),result:r.result??undefined,errorCode:r.error_code?String(r.error_code):null,iterationCount:Number(r.iteration_count??0),createdAt:new Date(String(r.created_at)).toISOString(),completedAt:r.completed_at?new Date(String(r.completed_at)).toISOString():null});
const toEvent=(r:Record<string,unknown>):TaskEventRecord=>({id:String(r.id),taskId:String(r.task_id),type:String(r.event_type),payload:r.payload,createdAt:new Date(String(r.created_at)).toISOString()});
const toWorkspace=(r:Record<string,unknown>):WorkspaceRecord=>({id:String(r.id),name:String(r.name),ownerId:String(r.owner_id),createdAt:new Date(String(r.created_at)).toISOString()});
const toApproval=(r:Record<string,unknown>):ApprovalRecord=>({id:String(r.id),taskId:String(r.task_id),workspaceId:String(r.workspace_id),toolCallId:r.tool_call_id?String(r.tool_call_id):null,tool:String(r.tool),input:r.input,status:String(r.status),requestedBy:r.requested_by?String(r.requested_by):null,decidedBy:r.decided_by?String(r.decided_by):null,reason:r.reason?String(r.reason):null,createdAt:new Date(String(r.created_at)).toISOString(),decidedAt:r.decided_at?new Date(String(r.decided_at)).toISOString():null});

class PostgresTaskRepository implements TaskRepository {
  constructor(private readonly sql:NeonQueryFunction<false,false>){}
  async create(input:CreateTaskInput){const rows=await this.sql`INSERT INTO tasks (workspace_id,prompt,mode,status,max_iterations,budget_cents) VALUES (${input.workspaceId}::uuid,${input.prompt},${input.mode},'queued',${input.maxIterations??12},${input.budgetCents??null}) RETURNING *`;return toTask(rows[0] as Record<string,unknown>)}
  async get(id:string){const rows=await this.sql`SELECT * FROM tasks WHERE id=${id}::uuid`;return rows.length?toTask(rows[0] as Record<string,unknown>):null}
  async claimNextQueued(){const rows=await this.sql`WITH next_task AS (SELECT id FROM tasks WHERE status='queued' ORDER BY created_at ASC FOR UPDATE SKIP LOCKED LIMIT 1) UPDATE tasks SET status='planning' WHERE id IN (SELECT id FROM next_task) RETURNING *`;return rows.length?toTask(rows[0] as Record<string,unknown>):null}
  async updateStatus(id:string,status:string){const rows=await this.sql`UPDATE tasks SET status=${status},completed_at=CASE WHEN ${status} IN ('completed','failed','cancelled') THEN now() ELSE completed_at END WHERE id=${id}::uuid RETURNING *`;return rows.length?toTask(rows[0] as Record<string,unknown>):null}
  async updateExecution(id:string,input:{status:string;result?:unknown;errorCode?:string;iterationCount:number}){const rows=await this.sql`UPDATE tasks SET status=${input.status},result=${input.result===undefined?null:JSON.stringify(input.result)}::jsonb,error_code=${input.errorCode??null},iteration_count=${input.iterationCount},completed_at=CASE WHEN ${input.status} IN ('completed','failed','cancelled') THEN now() ELSE completed_at END WHERE id=${id}::uuid RETURNING *`;return rows.length?toTask(rows[0] as Record<string,unknown>):null}
  async addEvent(taskId:string,type:string,payload:unknown){const rows=await this.sql`INSERT INTO task_events(task_id,event_type,payload) VALUES(${taskId}::uuid,${type},${JSON.stringify(payload)}::jsonb) RETURNING *`;return toEvent(rows[0] as Record<string,unknown>)}
  async listEvents(taskId:string){const rows=await this.sql`SELECT * FROM task_events WHERE task_id=${taskId}::uuid ORDER BY created_at ASC`;return rows.map(r=>toEvent(r as Record<string,unknown>))}
  async createWorkspace(input:{email:string;displayName?:string;workspaceName?:string}){const rows=await this.sql`WITH new_user AS (INSERT INTO users(email,display_name) VALUES(${input.email},${input.displayName??null}) ON CONFLICT(email) DO UPDATE SET display_name=COALESCE(EXCLUDED.display_name,users.display_name) RETURNING id) INSERT INTO workspaces(name,owner_id) SELECT ${input.workspaceName??'NexaForge Workspace'},id FROM new_user RETURNING *`;const workspace=toWorkspace(rows[0] as Record<string,unknown>);await this.sql`INSERT INTO workspace_members(workspace_id,user_id,role) VALUES(${workspace.id}::uuid,${workspace.ownerId}::uuid,'owner') ON CONFLICT DO NOTHING`;return workspace}
  async workspaceExists(id:string){const rows=await this.sql`SELECT 1 FROM workspaces WHERE id=${id}::uuid LIMIT 1`;return rows.length>0}
  async getUserByEmail(email:string){const rows=await this.sql`SELECT id,email,display_name FROM users WHERE email=${email} LIMIT 1`;if(!rows.length)return null;const r=rows[0] as Record<string,unknown>;return{id:String(r.id),email:String(r.email),displayName:r.display_name?String(r.display_name):null}}
  async getWorkspaceRole(workspaceId:string,userId:string){const rows=await this.sql`SELECT role FROM workspace_members WHERE workspace_id=${workspaceId}::uuid AND user_id=${userId}::uuid`;return rows.length?String((rows[0] as Record<string,unknown>).role) as WorkspaceRole:null}
  async createApproval(input:{taskId:string;workspaceId:string;toolCallId?:string;tool:string;input:unknown}){const rows=await this.sql`INSERT INTO approval_requests(task_id,workspace_id,tool_call_id,tool,input) VALUES(${input.taskId}::uuid,${input.workspaceId}::uuid,${input.toolCallId??null}::uuid,${input.tool},${JSON.stringify(input.input)}::jsonb) RETURNING *`;return toApproval(rows[0] as Record<string,unknown>)}
  async listApprovals(workspaceId:string,status?:string){const rows=status?await this.sql`SELECT * FROM approval_requests WHERE workspace_id=${workspaceId}::uuid AND status=${status} ORDER BY created_at DESC`:await this.sql`SELECT * FROM approval_requests WHERE workspace_id=${workspaceId}::uuid ORDER BY created_at DESC`;return rows.map(r=>toApproval(r as Record<string,unknown>))}
  async decideApproval(id:string,userId:string,status:'approved'|'rejected',reason?:string){const rows=await this.sql`UPDATE approval_requests SET status=${status},decided_by=${userId}::uuid,reason=${reason??null},decided_at=now() WHERE id=${id}::uuid AND status='pending' RETURNING *`;return rows.length?toApproval(rows[0] as Record<string,unknown>):null}
}
export function createTaskRepository(databaseUrl=process.env.DATABASE_URL):TaskRepository|null{if(!databaseUrl)return null;return new PostgresTaskRepository(neon(databaseUrl));}
