import type { AgentMode, AgentTask } from '@nexaforge/shared';
import { BoundedAgentExecutor, createConfiguredModelProvider, createSupervisor, createToolRegistry, echoTool, timeTool, webSearchTool } from '@nexaforge/ai-core';
import type { TaskRepository, TaskRecord } from '@nexaforge/db';
export type WorkerStore=TaskRepository;
const toAgentTask=(task:TaskRecord):AgentTask=>({id:task.id,workspaceId:task.workspaceId,prompt:task.prompt,mode:task.mode as AgentMode,status:task.status as AgentTask['status'],maxIterations:task.maxIterations,budgetCents:task.budgetCents??undefined});
const workerTools=[timeTool,echoTool,webSearchTool];
export class TaskWorker{
 private running=false; private readonly controllers=new Map<string,AbortController>(); private timer?:NodeJS.Timeout;
 constructor(private readonly store:WorkerStore,private readonly pollMs=750){}
 start(){if(this.running)return;this.running=true;void this.loop()}
 stop(){this.running=false;if(this.timer)clearTimeout(this.timer);for(const c of this.controllers.values())c.abort();this.controllers.clear()}
 cancel(taskId:string){const c=this.controllers.get(taskId);if(!c)return false;c.abort();return true}
 private async loop(){while(this.running){try{const task=await this.store.claimNextQueued();if(task)await this.process(task)}catch(error){console.error('[nexaforge-worker]',error)}if(!this.running)break;await new Promise<void>(resolve=>{this.timer=setTimeout(resolve,this.pollMs)})}}
 private async process(task:TaskRecord){const controller=new AbortController();this.controllers.set(task.id,controller);await this.store.addEvent(task.id,'task.planning',{worker:'default'});try{const model=createConfiguredModelProvider();const registry=createToolRegistry(workerTools);const runtime=createSupervisor(registry.list(),model);const executor=new BoundedAgentExecutor(runtime,registry);await this.store.updateStatus(task.id,'running');await this.store.addEvent(task.id,'task.running',{});if(controller.signal.aborted)throw new Error('TASK_CANCELLED');const result=await executor.run(toAgentTask({...task,status:'running'}));if(controller.signal.aborted)throw new Error('TASK_CANCELLED');const proposed=result.calls.filter(call=>call.status==='proposed');for(const call of proposed){await this.store.createApproval({taskId:task.id,workspaceId:task.workspaceId,toolCallId:call.id,tool:call.tool,input:call.input});await this.store.addEvent(task.id,'approval.requested',{toolCallId:call.id,tool:call.tool})}const status=proposed.length?'waiting':result.status;await this.store.updateExecution(task.id,{status,result:{answer:result.answer,calls:result.calls},iterationCount:result.calls.length,errorCode:status==='failed'?'EXECUTION_FAILED':undefined});await this.store.addEvent(task.id,`task.${status}`,{calls:result.calls.length,hasAnswer:Boolean(result.answer)})}catch(error){const message=error instanceof Error?error.message:'TASK_EXECUTION_FAILED';const cancelled=message==='TASK_CANCELLED'||controller.signal.aborted;await this.store.updateExecution(task.id,{status:cancelled?'cancelled':'failed',errorCode:cancelled?'TASK_CANCELLED':message,result:{error:message},iterationCount:task.iterationCount});await this.store.addEvent(task.id,cancelled?'task.cancelled':'task.failed',{error:message})}finally{this.controllers.delete(task.id)}}
}
export function configuredWorker(store:WorkerStore){return new TaskWorker(store)}
